---
# Set the AWS keys:
#
# export AWS_ACCESS_KEY_ID=ABCDEFGHIJK
# export AWS_SECRET_ACCESS_KEY=asdfghjkl098765434323
#
# Now run the playbook, supplying an instance name and EC2 creds
# Examples:
#
# ansible-playbook --private-key=~/.ssh/my-key-pair-name.pem -e "instance_id=neo4jdemo1 inst_name=neo4jdemo1 keypair=key-pair-name" neo4j-demo.yml


- name: Stage EBS AWS Server
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    instance_type: "c3.xlarge"
    security_groups: ['demo']
    region: eu-west-1
    image: { "m3.large": "ami-f4b11183", "c3.xlarge": "ami-f4b11183"}

  tasks:
    - name: Launch instance 
      local_action:
        module: ec2
        region: eu-west-1
        keypair: "{{ keypair }}"
        group: "{{ security_groups }}"
        instance_type: "{{ instance_type }}"
        #instance_profile_name: "{{ instance_profile_name }}"
        image: "{{ image[instance_type] }}"
        instance_tags: '{"Name":"{{ inst_name }}",  "systemtype":"neo4j-demo" }'
        id: "{{ instance_id }}"
        wait: true
      register: ec2
  
    - name: Report
      local_action: debug msg="Instance Launched."

    - debug: var=ec2
    - debug: var=item  
      with_items: ec2.instances

    - name: Add all instance public IPs to host group
      local_action: add_host hostname={{ item.public_ip }} groupname=ec2hosts
      with_items: ec2.instances

    - name: Wait for SSH to come up
      local_action: wait_for host={{ item.public_ip }} port=22 delay=60 timeout=320 state=started
      with_items: ec2.instances

- name: Configure Instance
  hosts: ec2hosts
  remote_user: ubuntu
  sudo: yes
  gather_facts: true

  roles:
   - neo4j
   - neo4j-demo
   