---
- name: Install nodejs (Jekyll has a requirement on a Javascript runtime)
  apt: name=nodejs state=present
  sudo: yes

- name: Install Bundler
  command: gem install bundler
  sudo: yes 

- name: Install github pages in project folder
  shell: /usr/local/rvm/gems/ruby-2.0.0-p648/wrappers/bundle install chdir=/vagrant
  sudo: yes
