---
- name: Wine | Install Wine and all Dependencies
  command: "{{ item }}" 
  sudo: yes
  with_items:
    - "dpkg --add-architecture i386"
    - "wget -nc https://dl.winehq.org/wine-builds/Release.key"
    - "apt-key add Release.key"
    - "apt-add-repository https://dl.winehq.org/wine-builds/ubuntu/"
    - "apt-get update"
    - "apt-get install -y winehq-stable"
