---
- name: Download Gatling
  sudo: yes
  get_url: url={{ gatling_url }} dest={{ install_dir }}

- name: Extract Gatling
  sudo: yes
  unarchive: copy=no src={{ install_dir }}/{{ gatling_archive }}.zip dest={{ install_dir }}

- name: Remove downloaded archive
  sudo: yes
  shell: "rm -f {{ install_dir }}/{{ gatling_archive }}.zip"
