---
- name: Prepare | Get the current users name
  shell: id -u -n
  register: user_name

- name: Prepare | Get the current users group
  shell: id -g -n
  register: user_group

- name: Install | Ensure dependencies installed 
  apt: pkg={{ item }} state=installed
  tags: [packages]
  sudo: yes
  with_items:
    - curl
    - libpq-dev
    - ruby-dev

- name: Install | Ensure RVM signature is installed
  shell: "gpg --keyserver hkp://keys.gnupg.net --recv-keys {{rvm_signature}}"

- name: Install | Ensure RVM is installed
  shell: curl -L {{rvm_download_location}} | bash -s stable --ruby creates=/home/{{user_name.stdout}}/.rvm

- name: Install | Ensure JRuby is installed as default
  shell: '/home/{{user_name.stdout}}/.rvm/bin/rvm install --default {{ruby_version}} creates=/usr/local/rvm/rubies/{{ruby_version}}'
